params:
  era: Run2_2016APV
  sampleType: data

SingleMuon_Run2016B-ver1_HIPM-UL: /SingleMuon/Run2016B-ver1_HIPM_UL2016_MiniAODv2-v2/MINIAO1_HIPM_UL2016_MiniAODv2_NanoAODv9-ULD
SingleMuon_Run2016B-ver2_HIPM-UL: /SingleMuon/Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleMuon_Run2016C-HIPM-UL: /SingleMuon/Run2016C-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleMuon_Run2016D-HIPM-UL: /SingleMuon/Run2016D-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleMuon_Run2016E-HIPM-UL: /SingleMuon/Run2016E-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleMuon_Run2016F-HIPM-UL: /SingleMuon/Run2016F-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleElectron_Run2016B-ver1_HIPM-UL: /SingleElectron/Run2016B-ver1_HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleElectron_Run2016B-ver2_HIPM-UL: /SingleElectron/Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleElectron_Run2016C-HIPM-UL: /SingleElectron/Run2016C-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleElectron_Run2016D-HIPM-UL: /SingleElectron/Run2016D-HIPM_UL2016_MiniAODv2-v2/MINIAOD
SingleElectron_Run2016E-HIPM-UL: /SingleElectron/Run2016E-HIPM_UL2016_MiniAODv2-v5/MINIAOD
SingleElectron_Run2016F-HIPM-UL: /SingleElectron/Run2016F-HIPM_UL2016_MiniAODv2-v2/MINIAOD
Tau_Run2016B-ver1_HIPM-UL: /Tau/Run2016B-ver1_HIPM_UL2016_MiniAODv2-v1/MINIAOD
Tau_Run2016B-ver2_HIPM-UL: /Tau/Run2016B-ver2_HIPM_UL2016_MiniAODv2-v1/MINIAOD
Tau_Run2016C-HIPM-UL: /Tau/Run2016C-HIPM_UL2016_MiniAODv2-v1/MINIAOD
Tau_Run2016D-HIPM-UL: /Tau/Run2016D-HIPM_UL2016_MiniAODv2-v1/MINIAOD
Tau_Run2016E-HIPM-UL: /Tau/Run2016E-HIPM_UL2016_MiniAODv2-v1/MINIAOD
Tau_Run2016F-HIPM-UL: /Tau/Run2016F-HIPM_UL2016_MiniAODv2-v1/MINIAOD
MET_Run2016B-ver1_HIPM-UL: /MET/Run2016B-ver1_HIPM_UL2016_MiniAODv2-v2/MINIAOD
MET_Run2016B-ver2_HIPM-UL: /MET/Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2/MINIAOD
MET_Run2016C-HIPM-UL: /MET/Run2016C-HIPM_UL2016_MiniAODv2-v2/MINIAOD
MET_Run2016D-HIPM-UL: /MET/Run2016D-HIPM_UL2016_MiniAODv2-v2/MINIAOD
MET_Run2016E-HIPM-UL: /MET/Run2016E-HIPM_UL2016_MiniAODv2-v2/MINIAOD
MET_Run2016F-HIPM-UL: /MET/Run2016F-HIPM_UL2016_MiniAODv2-v2/MINIAOD
