params:
  era: Run2_2017
  sampleType: data

SingleMuon_Run2017B-UL: /SingleMuon/Run2017B-UL2017_MiniAODv2-v1/MINIAOD
SingleMuon_Run2017C-UL: /SingleMuon/Run2017C-UL2017_MiniAODv2-v1/MINIAOD
SingleMuon_Run2017D-UL: /SingleMuon/Run2017D-UL2017_MiniAODv2-v1/MINIAOD
SingleMuon_Run2017E-UL: /SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD
SingleMuon_Run2017F-UL: /SingleMuon/Run2017F-UL2017_MiniAODv2-v1/MINIAOD
SingleElectron_Run2017B-UL: /SingleElectron/Run2017B-UL2017_MiniAODv2-v1/MINIAOD
SingleElectron_Run2017C-UL: /SingleElectron/Run2017C-UL2017_MiniAODv2-v1/MINIAOD
SingleElectron_Run2017D-UL: /SingleElectron/Run2017D-UL2017_MiniAODv2-v1/MINIAOD
SingleElectron_Run2017E-UL: /SingleElectron/Run2017E-UL2017_MiniAODv2-v1/MINIAOD
SingleElectron_Run2017F-UL: /SingleElectron/Run2017F-UL2017_MiniAODv2-v1/MINIAOD
Tau_Run2017B-UL: /Tau/Run2017B-UL2017_MiniAODv2-v1/MINIAOD
Tau_Run2017C-UL: /Tau/Run2017C-UL2017_MiniAODv2-v1/MINIAOD
Tau_Run2017D-UL: /Tau/Run2017D-UL2017_MiniAODv2-v1/MINIAOD
Tau_Run2017E-UL: /Tau/Run2017E-UL2017_MiniAODv2-v1/MINIAOD
Tau_Run2017F-UL: /Tau/Run2017F-UL2017_MiniAODv2-v1/MINIAOD
MET_Run2017B-UL: /MET/Run2017B-UL2017_MiniAODv2-v1/MINIAOD
MET_Run2017C-UL: /MET/Run2017C-UL2017_MiniAODv2-v1/MINIAOD
MET_Run2017D-UL: /MET/Run2017D-UL2017_MiniAODv2-v1/MINIAOD
MET_Run2017E-UL: /MET/Run2017E-UL2017_MiniAODv2-v1/MINIAOD
MET_Run2017F-UL: /MET/Run2017F-UL2017_MiniAODv2-v1/MINIAOD
