params:
  era: Run2_2018
  sampleType: data

SingleMuon_Run2018A-UL: /SingleMuon/Run2018A-UL2018_MiniAODv2-v3/MINIAOD
SingleMuon_Run2018B-UL: /SingleMuon/Run2018B-UL2018_MiniAODv2-v2/MINIAOD
SingleMuon_Run2018C-UL: /SingleMuon/Run2018C-UL2018_MiniAODv2-v2/MINIAOD
SingleMuon_Run2018D-UL: /SingleMuon/Run2018D-UL2018_MiniAODv2-v3/MINIAOD
EGamma_Run2018A-UL: /EGamma/Run2018A-UL2018_MiniAODv2-v1/MINIAOD
EGamma_Run2018B-UL: /EGamma/Run2018B-UL2018_MiniAODv2-v1/MINIAOD
EGamma_Run2018C-UL: /EGamma/Run2018C-UL2018_MiniAODv2-v1/MINIAOD
EGamma_Run2018D-UL: /EGamma/Run2018D-UL2018_MiniAODv2-v2/MINIAOD
Tau_Run2018A-UL: /Tau/Run2018A-UL2018_MiniAODv2-v1/MINIAOD
Tau_Run2018B-UL: /Tau/Run2018B-UL2018_MiniAODv2-v2/MINIAOD
Tau_Run2018C-UL: /Tau/Run2018C-UL2018_MiniAODv2-v1/MINIAOD
Tau_Run2018D-UL: /Tau/Run2018D-UL2018_MiniAODv2-v1/MINIAOD
MET_Run2018A-UL: /MET/Run2018A-UL2018_MiniAODv2-v2/MINIAOD
MET_Run2018B-UL: /MET/Run2018B-UL2018_MiniAODv2-v2/MINIAOD
MET_Run2018C-UL: /MET/Run2018C-UL2018_MiniAODv2-v1/MINIAOD
MET_Run2018D-UL: /MET/Run2018D-UL2018_MiniAODv2-v1/MINIAOD
